# Generated by Django 4.2 on 2025-10-31 18:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_username', models.CharField(default='master_parser', max_length=255, verbose_name='Username бота')),
                ('is_running', models.BooleanField(default=False, verbose_name='Запущен')),
                ('last_heartbeat', models.DateTimeField(auto_now=True, verbose_name='Последний heartbeat')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Время запуска')),
                ('total_chats_monitored', models.IntegerField(default=0, verbose_name='Всего чатов мониторится')),
                ('total_users', models.IntegerField(default=0, verbose_name='Всего пользователей')),
                ('messages_processed_today', models.IntegerField(default=0, verbose_name='Сообщений обработано сегодня')),
                ('messages_processed_total', models.IntegerField(default=0, verbose_name='Всего сообщений обработано')),
                ('errors_count', models.IntegerField(default=0, verbose_name='Количество ошибок')),
                ('last_error', models.TextField(blank=True, verbose_name='Последняя ошибка')),
                ('last_error_at', models.DateTimeField(blank=True, null=True, verbose_name='Время последней ошибки')),
            ],
            options={
                'verbose_name': 'Статус бота',
                'verbose_name_plural': 'Статус бота',
            },
        ),
        migrations.CreateModel(
            name='KeywordGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Название группы')),
                ('keywords', models.JSONField(default=list, help_text='Список ключевых слов для поиска', verbose_name='Ключевые слова')),
                ('use_ai_filter', models.BooleanField(default=False, help_text='Дополнительная проверка сообщений через ИИ', verbose_name='Использовать AI фильтр')),
                ('ai_prompt', models.TextField(blank=True, help_text='Инструкция для ИИ по фильтрации сообщений', verbose_name='Промт для AI')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Группа ключевых слов',
                'verbose_name_plural': 'Группы ключевых слов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MonitoredChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(help_text='Telegram ID чата для мониторинга', verbose_name='ID чата')),
                ('chat_name', models.CharField(blank=True, max_length=255, verbose_name='Название чата')),
                ('chat_username', models.CharField(blank=True, help_text='@username чата (если есть)', max_length=255, verbose_name='Username чата')),
                ('invite_link', models.URLField(blank=True, verbose_name='Ссылка на чат')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('last_message_at', models.DateTimeField(blank=True, null=True, verbose_name='Последнее сообщение')),
            ],
            options={
                'verbose_name': 'Мониторимый чат',
                'verbose_name_plural': 'Мониторимые чаты',
                'ordering': ['-added_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.BigIntegerField(verbose_name='ID сообщения')),
                ('chat_id', models.BigIntegerField(verbose_name='ID чата')),
                ('sender_id', models.BigIntegerField(blank=True, null=True, verbose_name='ID отправителя')),
                ('sender_name', models.CharField(blank=True, max_length=255, verbose_name='Имя отправителя')),
                ('sender_username', models.CharField(blank=True, max_length=255, verbose_name='Username отправителя')),
                ('message_text', models.TextField(verbose_name='Текст сообщения')),
                ('message_link', models.URLField(blank=True, verbose_name='Ссылка на сообщение')),
                ('matched_keywords', models.JSONField(default=list, verbose_name='Найденные ключевые слова')),
                ('ai_result', models.TextField(blank=True, verbose_name='Результат AI проверки')),
                ('ai_score', models.FloatField(blank=True, help_text='Оценка релевантности от 0 до 1', null=True, verbose_name='AI Score')),
                ('notification_sent', models.BooleanField(default=False, verbose_name='Уведомление отправлено')),
                ('crm_status', models.CharField(choices=[('new', 'Новое'), ('in_progress', 'В работе'), ('completed', 'Завершено'), ('rejected', 'Отклонено')], default='new', max_length=20, verbose_name='CRM Статус')),
                ('is_processed', models.BooleanField(default=False, help_text='Пользователь просмотрел сообщение', verbose_name='Обработано')),
                ('is_qualified', models.BooleanField(default=False, help_text='Сообщение признано качественным лидом', verbose_name='Квалифицированный лид')),
                ('dialog_started', models.BooleanField(default=False, help_text='С пользователем начали диалог', verbose_name='Диалог начат')),
                ('sale_made', models.BooleanField(default=False, verbose_name='Продажа совершена')),
                ('notes', models.TextField(blank=True, help_text='Дополнительные заметки пользователя', verbose_name='Заметки')),
                ('processed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата обработки')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('keyword_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processed_messages', to='telegram_parser.keywordgroup', verbose_name='Группа ключевых слов')),
                ('monitored_chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processed_messages', to='telegram_parser.monitoredchat', verbose_name='Мониторимый чат')),
            ],
            options={
                'verbose_name': 'Обработанное сообщение',
                'verbose_name_plural': 'Обработанные сообщения',
                'ordering': ['-processed_at'],
            },
        ),
    ]
