# Generated by Django 4.2 on 2025-10-31 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('telegram_parser', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='processedmessage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processed_messages', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='monitoredchat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitored_chats', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='keywordgroup',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyword_groups', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddIndex(
            model_name='processedmessage',
            index=models.Index(fields=['user', 'processed_at'], name='telegram_pa_user_id_972626_idx'),
        ),
        migrations.AddIndex(
            model_name='processedmessage',
            index=models.Index(fields=['is_qualified', 'processed_at'], name='telegram_pa_is_qual_cf133f_idx'),
        ),
        migrations.AddIndex(
            model_name='processedmessage',
            index=models.Index(fields=['notification_sent'], name='telegram_pa_notific_11fb66_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='processedmessage',
            unique_together={('user', 'message_id', 'chat_id')},
        ),
        migrations.AlterUniqueTogether(
            name='monitoredchat',
            unique_together={('user', 'chat_id')},
        ),
        migrations.AlterUniqueTogether(
            name='keywordgroup',
            unique_together={('user', 'name')},
        ),
    ]
