# Generated by Django 4.2 on 2025-10-31 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('telegram_parser', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(unique=True, verbose_name='ID чата Telegram')),
                ('name', models.CharField(max_length=500, verbose_name='Название чата')),
                ('invite_link', models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на чат')),
                ('is_active', models.BooleanField(default=True, verbose_name='Чат активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Глобальный чат',
                'verbose_name_plural': 'Глобальные чаты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserChatSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Включен для пользователя')),
                ('enabled_at', models.DateTimeField(auto_now_add=True, verbose_name='Включен')),
                ('disabled_at', models.DateTimeField(blank=True, null=True, verbose_name='Выключен')),
                ('global_chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_settings', to='telegram_parser.globalchat', verbose_name='Глобальный чат')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_settings', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Настройка чата пользователя',
                'verbose_name_plural': 'Настройки чатов пользователей',
            },
        ),
        migrations.AddIndex(
            model_name='globalchat',
            index=models.Index(fields=['chat_id'], name='telegram_pa_chat_id_45abc3_idx'),
        ),
        migrations.AddIndex(
            model_name='globalchat',
            index=models.Index(fields=['is_active'], name='telegram_pa_is_acti_df8796_idx'),
        ),
        migrations.AddIndex(
            model_name='userchatsettings',
            index=models.Index(fields=['user', 'is_enabled'], name='telegram_pa_user_id_a10e97_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userchatsettings',
            unique_together={('user', 'global_chat')},
        ),
    ]
