# Generated by Django 4.2 on 2025-11-11 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_parser', '0004_rawmessage_rawmessage_telegram_pa_receive_5ed51f_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='keywordgroup',
            name='notification_chat_id',
            field=models.BigIntegerField(blank=True, help_text='ID чата Telegram, куда отправлять уведомления по этой группе ключевых слов', null=True, verbose_name='Chat ID для уведомлений'),
        ),
    ]
