# Generated by Django 4.2 on 2025-11-11 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('telegram_parser', '0005_keywordgroup_notification_chat_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentMessageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_username', models.CharField(blank=True, max_length=255, verbose_name='Username получателя')),
                ('recipient_user_id', models.BigIntegerField(blank=True, null=True, verbose_name='Telegram ID получателя')),
                ('recipient_name', models.CharField(max_length=500, verbose_name='Имя получателя')),
                ('sent_message_text', models.TextField(verbose_name='Текст отправленного сообщения')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время отправки')),
                ('sent_from_account', models.CharField(help_text='Username sender-аккаунта с которого отправили', max_length=255, verbose_name='Sender-аккаунт')),
                ('sent_from_phone', models.CharField(blank=True, help_text='Номер телефона sender-аккаунта для точной идентификации', max_length=20, verbose_name='Телефон sender-аккаунта')),
                ('is_delivered', models.BooleanField(default=True, verbose_name='Доставлено')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Время прочтения')),
                ('is_replied', models.BooleanField(default=False, verbose_name='Получен ответ')),
                ('replied_at', models.DateTimeField(blank=True, null=True, verbose_name='Время ответа')),
                ('reply_text', models.TextField(blank=True, verbose_name='Текст ответа')),
                ('telegram_message_id', models.BigIntegerField(blank=True, null=True, verbose_name='ID сообщения в Telegram')),
                ('chat_id', models.BigIntegerField(blank=True, null=True, verbose_name='ID диалога в Telegram')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('processed_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_history', to='telegram_parser.processedmessage', verbose_name='Исходное сообщение-лид')),
                ('template_used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='telegram_parser.messagetemplate', verbose_name='Использованный шаблон')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Отправленное сообщение',
                'verbose_name_plural': 'Отправленные сообщения',
                'ordering': ['-sent_at'],
                'indexes': [
                    models.Index(fields=['user', '-sent_at'], name='telegram_pa_user_id_sent_at_idx'),
                    models.Index(fields=['sent_from_account', '-sent_at'], name='telegram_pa_sent_fr_sent_at_idx'),
                    models.Index(fields=['recipient_username'], name='telegram_pa_recipie_idx'),
                    models.Index(fields=['is_read', 'is_replied'], name='telegram_pa_is_read_is_repl_idx'),
                    models.Index(fields=['-sent_at'], name='telegram_pa_sent_at_idx'),
                ],
            },
        ),
    ]
