# Generated by Django 4.2.7 on 2025-01-11 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_parser', '0015_rename_telegram_pa_user_id_sent_at_idx_telegram_pa_user_id_bb5b98_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedmessage',
            name='ai_approved',
            field=models.BooleanField(default=True, verbose_name='Одобрено AI'),
        ),
    ]
