# Generated by Django 4.2.7 on 2025-01-12 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('telegram_parser', '0016_processedmessage_ai_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='SenderAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: Рабочий аккаунт, Резервный и т.д.', max_length=100, verbose_name='Название аккаунта')),
                ('phone', models.CharField(help_text='Номер в международном формате', max_length=20, verbose_name='Номер телефона')),
                ('api_id', models.IntegerField(help_text='API ID от my.telegram.org', verbose_name='API ID')),
                ('api_hash', models.CharField(help_text='API Hash от my.telegram.org', max_length=255, verbose_name='API Hash')),
                ('session_string', models.TextField(blank=True, help_text='Строка сессии Telegram', verbose_name='Session String')),
                ('phone_code_hash', models.CharField(blank=True, help_text='Временный хеш для авторизации', max_length=255, verbose_name='Phone Code Hash')),
                ('is_active', models.BooleanField(default=True, help_text='Использовать этот аккаунт для отправки', verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_accounts', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Sender-аккаунт',
                'verbose_name_plural': 'Sender-аккаунты',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='telegram_pa_user_id_b5c4a7_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='senderaccount',
            constraint=models.UniqueConstraint(fields=('user', 'phone'), name='unique_user_phone'),
        ),
    ]
