# Generated by Django 4.2.7 on 2025-01-12 00:10

from django.db import migrations


def migrate_sender_accounts(apps, schema_editor):
    """Переносим существующие sender данные из User в SenderAccount"""
    User = apps.get_model('users', 'User')
    SenderAccount = apps.get_model('telegram_parser', 'SenderAccount')
    
    # Находим всех пользователей с подключенными sender-аккаунтами
    users_with_sender = User.objects.filter(
        sender_api_id__isnull=False,
        sender_api_hash__isnull=False,
        sender_phone__isnull=False
    ).exclude(sender_phone='')
    
    for user in users_with_sender:
        # Создаем новую запись SenderAccount из данных User
        SenderAccount.objects.get_or_create(
            user=user,
            phone=user.sender_phone,
            defaults={
                'name': 'Основной аккаунт',
                'api_id': user.sender_api_id,
                'api_hash': user.sender_api_hash,
                'session_string': user.sender_session_string or '',
                'phone_code_hash': user.sender_phone_code_hash or '',
                'is_active': True,
            }
        )
    
    print(f"Migrated {users_with_sender.count()} sender accounts")


def reverse_migration(apps, schema_editor):
    """Обратная миграция - удаляем все SenderAccount записи"""
    SenderAccount = apps.get_model('telegram_parser', 'SenderAccount')
    count = SenderAccount.objects.count()
    SenderAccount.objects.all().delete()
    print(f"Deleted {count} sender accounts")


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_parser', '0017_senderaccount'),
        ('users', '0001_initial'),  # Зависимость от модели User
    ]

    operations = [
        migrations.RunPython(migrate_sender_accounts, reverse_migration),
    ]
