# Generated by Django 4.2.7 on 2025-01-12 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_parser', '0018_migrate_sender_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='senderaccount',
            name='initial_delay_min',
            field=models.IntegerField(default=30, help_text='Минимальная задержка перед первой отправкой сообщения', verbose_name='Мин. задержка перед отправкой (сек)'),
        ),
        migrations.AddField(
            model_name='senderaccount',
            name='initial_delay_max',
            field=models.IntegerField(default=60, help_text='Максимальная задержка перед первой отправкой сообщения', verbose_name='Макс. задержка перед отправкой (сек)'),
        ),
        migrations.AddField(
            model_name='senderaccount',
            name='message_delay_min',
            field=models.IntegerField(default=60, help_text='Минимальная пауза между отправкой сообщений', verbose_name='Мин. задержка между сообщениями (сек)'),
        ),
        migrations.AddField(
            model_name='senderaccount',
            name='message_delay_max',
            field=models.IntegerField(default=180, help_text='Максимальная пауза между отправкой сообщений', verbose_name='Макс. задержка между сообщениями (сек)'),
        ),
        migrations.AddField(
            model_name='senderaccount',
            name='daily_limit',
            field=models.IntegerField(default=30, help_text='Максимальное количество сообщений в сутки', verbose_name='Лимит сообщений в день'),
        ),
        migrations.AddField(
            model_name='senderaccount',
            name='messages_sent_today',
            field=models.IntegerField(default=0, help_text='Счетчик отправленных сообщений за сегодня', verbose_name='Отправлено сегодня'),
        ),
        migrations.AddField(
            model_name='senderaccount',
            name='last_message_date',
            field=models.DateField(blank=True, help_text='Дата последней отправки (для сброса счетчика)', null=True, verbose_name='Дата последнего сообщения'),
        ),
    ]
