# Generated by Django 4.2 on 2025-10-31 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_parser', '0003_globalchat_userchatsettings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.BigIntegerField(verbose_name='ID сообщения')),
                ('chat_id', models.BigIntegerField(verbose_name='ID чата')),
                ('chat_name', models.CharField(blank=True, max_length=500, verbose_name='Название чата')),
                ('sender_id', models.BigIntegerField(blank=True, null=True, verbose_name='ID отправителя')),
                ('sender_name', models.CharField(blank=True, max_length=255, verbose_name='Имя отправителя')),
                ('sender_username', models.CharField(blank=True, max_length=255, verbose_name='Username отправителя')),
                ('message_text', models.TextField(verbose_name='Текст сообщения')),
                ('message_date', models.DateTimeField(verbose_name='Дата сообщения')),
                ('is_channel_post', models.BooleanField(default=False, verbose_name='Пост канала')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='Получено парсером')),
            ],
            options={
                'verbose_name': 'Сырое сообщение',
                'verbose_name_plural': 'Сырые сообщения',
                'ordering': ['-received_at'],
            },
        ),
        migrations.AddIndex(
            model_name='rawmessage',
            index=models.Index(fields=['-received_at'], name='telegram_pa_receive_5ed51f_idx'),
        ),
        migrations.AddIndex(
            model_name='rawmessage',
            index=models.Index(fields=['chat_id'], name='telegram_pa_chat_id_f7bb91_idx'),
        ),
    ]
